updated registry

diff --git a/aws/qualyscs_sizing_aws b/aws/qualyscs_sizing_aws
--- a/aws/qualyscs_sizing_aws
+++ b/aws/qualyscs_sizing_aws
@@ -264,7 +264,7 @@ qualyscs_sizing_aws_general_command() {
 
   }
   resetGlobalCounters() {
-    	EKS_INSTANCE_COUNT_GLOBAL=0
+    EKS_INSTANCE_COUNT_GLOBAL=0
   	ECS_INSTANCE_COUNT_GLOBAL=0
   	ECS_FARGATE_TASK_COUNT_GLOBAL=0
 
@@ -404,15 +404,6 @@ qualyscs_sizing_aws_general_command() {
     fi
   }
 
-  # aws_eks_describe_cluster() {
-  #   RESULT=$(aws eks describe-cluster --name="${1}" --output json 2>/dev/null)
-  #   if [ $? -eq 0 ]; then
-  #     echo "${RESULT}"
-  #   else
-  #     echo '{"Error": [] }'
-  #     exit -1
-  #   fi
-  # }
   computeResourceSizing(){
     resetAccountCounters
     resetGlobalCounters
@@ -524,17 +515,19 @@ qualyscs_sizing_aws_registry_command() {
   fi
 
   resetAccountCounters() {
-    ECR_REPO_COUNT_GLOBAL=0
+       ECR_REPO_COUNT=0
+       ECR_IMAGE_COUNT=0
   }
   resetGlobalCounters() {
-    	ECR_REPO_COUNT_GLOBAL=0
-  	USE_AWS_ORG=false
+    	 ECR_REPO_COUNT_GLOBAL=0
+       ECR_IMAGE_COUNT_GLOBAL=0
+  	   USE_AWS_ORG=false
   }
 
   getAccountList() {
     if [ "${USE_AWS_ORG}" = "true" ]; then
-      echo "###################################################################################"
-      echo "Querying AWS Organization"
+      info "###################################################################################"
+      info "Querying AWS Organization"
       MASTER_ACCOUNT_ID=$(aws_organizations_describe_organization | jq -r '.Organization.MasterAccountId' 2>/dev/null)
       if [ $? -ne 0 ] || [ -z "${MASTER_ACCOUNT_ID}" ]; then
         logErrorExit "Error: Failed to describe AWS Organization, check aws cli setup, and access to the AWS Organizations API."
@@ -549,9 +542,9 @@ qualyscs_sizing_aws_registry_command() {
         error_and_exit "Error: Failed to list AWS Organization accounts, check aws cli setup, and access to the AWS Organizations API."
       fi
       TOTAL_ACCOUNTS=$(echo "${ACCOUNT_LIST}" | jq '.Accounts | length' 2>/dev/null)
-      echo "  Total number of member accounts: ${TOTAL_ACCOUNTS}"
-      echo "###################################################################################"
-      echo ""
+      info "  Total number of member accounts: ${TOTAL_ACCOUNTS}"
+      info "###################################################################################"
+      info ""
     else
       MASTER_ACCOUNT_ID=""
       ACCOUNT_LIST=""
@@ -572,16 +565,10 @@ qualyscs_sizing_aws_registry_command() {
       echo "  Warning: Using default region list"
       REGION_LIST=(us-east-1 us-east-2 us-west-1 us-west-2 ap-south-1 ap-northeast-1 ap-northeast-2 ap-southeast-1 ap-southeast-2 eu-north-1 eu-central-1 eu-west-1 sa-east-1 eu-west-2 eu-west-3 ca-central-1)
     fi
-    echo "###################################################################################"
-    echo "  Total number of regions: ${#REGION_LIST[@]}"
-    echo "###################################################################################"
-    echo ""
-  }
-  logErrorExit() {
-    echo
-    echo "ERROR: ${1}"
-    echo
-    exit 1
+    info "###################################################################################"
+    info "  Total number of regions: ${#REGION_LIST[@]}"
+    info "###################################################################################"
+
   }
 
   aws_organizations_describe_organization() {
@@ -605,13 +592,16 @@ qualyscs_sizing_aws_registry_command() {
     fi
   }
   aws_ecr_describe_repositories() {
-  # aws ecr describe-repositories | jq '.repositories[].repositoryName' | sed s/\"//g
-    RESULT=$(aws ecr describe-repositories  --region="${1}" | jq '.repositories[].repositoryName' | sed s/\"//g 2>/dev/null)
+    #aws ecr describe-repositories --region="${1}"
+
+  #  RESULT=$(aws ecr describe-repositories  --region="${1}" | jq '.repositories[].repositoryName' | sed s/\"//g 2>/dev/null)
+    RESULT=$(aws ecr describe-repositories  --region="${1}" | jq  2>/dev/null)
     if [ $? -eq 0 ]; then
       echo "${RESULT}"
     else
       echo '{"Error": [] }'
     fi
+     Filelog "Info"  "aws_ecr_describe_repositories:  ${RESULT}"
   }
   aws_ec2_describe_regions() {
     RESULT=$(aws ec2 describe-regions --output json 2>/dev/null)
@@ -619,11 +609,58 @@ qualyscs_sizing_aws_registry_command() {
       echo "${RESULT}"
     fi
   }
+
+  aws_ecr_list_images() {
+    IMAGE_JSON=$(aws ecr list-images --repository-name "${1}" --output json 2>/dev/null)
+    if [ $? -eq 0 ]; then
+       echo "${IMAGE_JSON}"
+    else
+      echo '{"Error": [] }'
+      exit -1
+    fi
+  }
+
+  get_image_count_from_image_json() {
+
+    IMAGE_COUNT=$(jq '.imageIds | length' <<< "${1}" 2>/dev/null)
+    if [ $? -eq 0 ]; then
+       echo "${IMAGE_COUNT}"
+    else
+      echo '{"Error": [] }'
+      exit -1
+    fi
+  }
+  get_total_image_count_from_repos() {
+    # Set the repository name
+    repository_name=${1}
+    region=${2}
+    FilelogDebug "get_total_image_count_from_repos : ${repository_name}"
+    # Initialize the total image count to 0
+    total_image_count=0
+
+    total_image_count=$(aws ecr list-images --repository-name "$repository_name" --region "$region" --query 'imageIds | length(@)' --output text)
+    FilelogDebug "total_image_count : ${total_image_count}"
+    FilelogDebug "aws ecr list-images --repository-name "$repository_name" --region "$region" --query 'imageIds | length(@)' --output text"
+    echo "${total_image_count}"
+  }
+
+  get_total_size_from_image_json() {
+
+    TOTAL_IMAGE_SIZE=$(jq -s 'add | .[].imageSizeInBytes' <<<"${1}" 2>/dev/null)
+    if [ $? -eq 0 ]; then
+       echo "${TOTAL_IMAGE_SIZE}"
+    else
+      echo '{"Error": [] }'
+      exit -1
+    fi
+  }
   computeResourceSizing(){
     resetAccountCounters
     resetGlobalCounters
+    TOTAL_REPOS=0
+    TOTAL_IMAGES=0
 
-     for ((ACCOUNT_INDEX=0; ACCOUNT_INDEX<=(TOTAL_ACCOUNTS-1); ACCOUNT_INDEX++))
+    for ((ACCOUNT_INDEX=0; ACCOUNT_INDEX<=(TOTAL_ACCOUNTS-1); ACCOUNT_INDEX++))
     do
       if [ "${USE_AWS_ORG}" = "true" ]; then
         ACCOUNT_NAME=$(echo "${ACCOUNT_LIST}" | jq -r .Accounts["${ACCOUNT_INDEX}"].Name 2>/dev/null)
@@ -635,37 +672,53 @@ qualyscs_sizing_aws_registry_command() {
         fi
       fi
 
-      echo "###################################################################################"
-      echo "Detecting AWS ECR"
+      info "Scanning AWS ECR"
       for i in "${REGION_LIST[@]}"
       do
-        RESOURCE_COUNT="0" # reset
-        CLUSTERS_JSON=$(aws_ecr_describe_repositories "${i}"  2>/dev/null)
-        RESOURCE_COUNT=$(echo $CLUSTERS_JSON | jq '. | length' 2>/dev/null)
-        echo "  Total # of ECR repositories in Region ${i}: ${RESOURCE_COUNT}"
-        # EKS_CLUSTER_COUNT=$((EKS_CLUSTER_COUNT + RESOURCE_COUNT))
+        TOTAL_REPOS=0
 
-        # if  [ $((RESOURCE_COUNT)) -ne 0 ]; then # only proceed if resource is not equal zero
-  	  # for row in $(echo $CLUSTERS_JSON | jq -r '.[] ');
+        REPOS_JSON=$(aws_ecr_describe_repositories "${i}"  2>/dev/null)
 
-  	  #   do
-  	# 	# TODO - extract relevant information about the clusters - such as number of nodes,
+        if jq -e '. == {"repositories": []}' <<< "$REPOS_JSON" > /dev/null; then
+          # JSON matches the expected format
+          info "Region: ${i} Repository: none"
+          continue
+        else
+          # JSON does not match the expected format
+          info "Region: ${i} Repository: "
+          mkdir -p ./output-ecr
+          echo $REPOS_JSON > ./output-ecr/${i}-repos.json
 
-  	# 	# k8s versions.
-     	# 	cluster_name=$row
-      # 	CLUSTER_OUTPUT=$(aws eks describe-cluster --name=$cluster_name --output json 2>/dev/null)
-      # 	mkdir -p ./output
-  	  #   echo $CLUSTER_OUTPUT > ./output/${row}-cluster-info.json
-        #   # https://docs.aws.amazon.com/cli/latest/reference/eks/describe-cluster.html
-        #   # https://docs.aws.amazon.com/eks/latest/userguide/eks-compute.html
-        #   NODEGROUP_OUTPUT=$(aws eks list-nodegroups --cluster-name=$cluster_name --output json 2>/dev/null)
-      # 	mkdir -p ./output
-  	  #   echo $NODEGROUP_OUTPUT > ./output/${row}-nodegroups.json
-  	  # done
+          # Use jq to count the number of repositories
+          REPOS_NAMES=($(jq -r '.repositories[].repositoryName' <<< "$REPOS_JSON"))
+
+          FilelogDebug "REPOS_NAMES : ${REPOS_NAMES}"
+
+            # Iterate over the repository names
+            for repository_name in "${REPOS_NAMES[@]}"; do
+
+              images_count=$(get_total_image_count_from_repos "${repository_name}" "${i}")
+              FilelogDebug "repository_name : ${repository_name}"
+              FilelogDebug "images_count : ${images_count}"
+              TOTAL_REPOS=$((TOTAL_REPOS + 1))
+              TOTAL_IMAGES=$((TOTAL_IMAGES + images_count))
+            done
+
+          info "  Total # of ECR repositories in Region ${i}: ${TOTAL_IMAGES}"
+          info "  Total # of ECR images in Region ${i}: ${TOTAL_IMAGES}"
+
+        fi
+        ECR_IMAGE_COUNT_GLOBAL=$((ECR_IMAGE_COUNT_GLOBAL + TOTAL_IMAGES))
+        ECR_REPO_COUNT_GLOBAL=$((ECR_REPO_COUNT_GLOBAL + TOTAL_REPOS))
 
       done
-      echo "Total ECR Instances across all regions: TBD"
-      echo "###################################################################################"
+
+      info "###################################################################################"
+
+      info "Total ECR Repositories across all regions:   ${ECR_REPO_COUNT_GLOBAL}"
+      info "Total ECR Images across all regions:   ${ECR_IMAGE_COUNT_GLOBAL}"
+
+      info "###################################################################################"
 
       #reset_account_counters
 
@@ -683,22 +736,21 @@ qualyscs_sizing_aws_registry_command() {
   #ECS_FARGATE_CLUSTERS=$(aws_ecs_list_clusters "${REGION}")
   #EKS_INSTANCE_COUNT_GLOBAL=$(aws_eks_list_clusters "${REGION}")
 
-  echo "###################################################################################"
-  echo " Qualys Container Security - Sizing tool for AWS "
-  echo " For AWS ECR Registry"
-  echo "###################################################################################"
+  info "###################################################################################"
+  info " Qualys Container Security - Sizing tool for AWS "
+  info " For AWS ECR Registry"
+  info "###################################################################################"
 
   getAccountList
   getRegionList
   computeResourceSizing
 
-  echo "###################################################################################"
   # echo "AWS EKS Cluster:"
   # echo "  Total # of ECS Fargate Task Instances:     ${ECS_FARGATE_TASK_COUNT_GLOBAL}"
   # echo "  Total # of EKS Instances:     ${EKS_INSTANCE_COUNT_GLOBAL}"
 
-  echo ""
-  echo "###################################################################################"
+  # echo ""
+  # echo "###################################################################################"
 
 }
 
@@ -889,7 +941,117 @@ initialize() {
   set -e
 
   # src/initialize.sh
+  cecho () {
 
+      declare -A colors;
+      colors=(\
+          ['black']='\E[0;47m'\
+          ['red']='\E[0;31m'\
+          ['green']='\E[0;32m'\
+          ['yellow']='\E[0;33m'\
+          ['blue']='\E[0;34m'\
+          ['magenta']='\E[0;35m'\
+          ['cyan']='\E[0;36m'\
+          ['white']='\E[0;37m'\
+      );
+
+      local defaultMSG="No message passed.";
+      local defaultColor="black";
+      local defaultNewLine=true;
+
+      while [[ $# -gt 1 ]];
+      do
+      key="$1";
+
+      case $key in
+          -c|--color)
+              color="$2";
+              shift;
+          ;;
+          -n|--noline)
+              newLine=false;
+          ;;
+          *)
+              # unknown option
+          ;;
+      esac
+      shift;
+      done
+
+      message=${1:-$defaultMSG};   # Defaults to default message.
+      color=${color:-$defaultColor};   # Defaults to default color, if not specified.
+      newLine=${newLine:-$defaultNewLine};
+
+      echo -en "${colors[$color]}";
+      echo -en "$message";
+      if [ "$newLine" = true ] ; then
+          echo;
+      fi
+      tput sgr0; #  Reset text attributes to normal without clearing screen.
+
+      return;
+  }
+
+  logErrorExit() {
+    echo
+    echo "ERROR: ${1}"
+    #cecho -c 'red' "ERROR: $@";
+    echo
+    exit 1
+  }
+  debug () {
+
+      cecho -c 'green' "$@";
+      FilelogDebug
+  }
+  warning () {
+
+      cecho -c 'yellow' "$@";
+      Filelog
+  }
+
+  error () {
+
+      cecho -c 'red' "$@";
+      Filelog
+  }
+
+  info () {
+
+      cecho -c 'blue' "$@";
+      Filelog "INFO" "$@";
+  }
+
+  FilelogDebug() {
+    # Set the message and optional log level
+    local message=$1
+    local level=${2:-DEBUG}
+
+    # Set the log file location
+    local log_file="./debug.log"
+    #local log_file="/var/log/my-log.log"
+
+    # Set the current time
+    local time=$(date "+%Y-%m-%d %H:%M:%S")
+
+    # Write the log message to the log file
+    echo "$time [$level] $message" >> "$log_file"
+  }
+
+  Filelog() {
+    # Set the log level and message
+    local level=$1
+    local message=$2
+
+    # Set the log file location
+    local log_file="./log.log"
+
+    # Set the current time
+    local time=$(date "+%Y-%m-%d %H:%M:%S")
+
+    # Write the log message to the log file
+    echo "$time [$level] $message" >> "$log_file"
+  }
 }
 
 # :command.run
