Separate commands for different sensors

diff --git a/aws/qualyscs_sizing_aws b/aws/qualyscs_sizing_aws
--- a/aws/qualyscs_sizing_aws
+++ b/aws/qualyscs_sizing_aws
@@ -34,7 +34,8 @@ qualyscs_sizing_aws_usage() {
   echo
   # :command.usage_commands
   printf "Commands:\n"
-  echo "  generate   Qualys Container Security - Sizing tool"
+  echo "  general    Generate sizing for General Sensor(s)"
+  echo "  registry   Generate sizing for Registry Sensor(s)"
   echo
 
   # :command.long_usage
@@ -61,20 +62,20 @@ qualyscs_sizing_aws_usage() {
 }
 
 # :command.usage
-qualyscs_sizing_aws_generate_usage() {
+qualyscs_sizing_aws_general_usage() {
   if [[ -n $long_usage ]]; then
-    printf "qualyscs_sizing_aws generate - Qualys Container Security - Sizing tool\n"
+    printf "qualyscs_sizing_aws general - Generate sizing for General Sensor(s)\n"
     echo
 
   else
-    printf "qualyscs_sizing_aws generate - Qualys Container Security - Sizing tool\n"
+    printf "qualyscs_sizing_aws general - Generate sizing for General Sensor(s)\n"
     echo
 
   fi
 
   printf "Usage:\n"
-  printf "  qualyscs_sizing_aws generate [TARGET]\n"
-  printf "  qualyscs_sizing_aws generate --help | -h\n"
+  printf "  qualyscs_sizing_aws general [OUTPUT]\n"
+  printf "  qualyscs_sizing_aws general --help | -h\n"
   echo
 
   # :command.long_usage
@@ -90,7 +91,7 @@ qualyscs_sizing_aws_generate_usage() {
     printf "Arguments:\n"
 
     # :argument.usage
-    echo "  TARGET"
+    echo "  OUTPUT"
     printf "    output file\n"
     echo
 
@@ -104,8 +105,51 @@ qualyscs_sizing_aws_generate_usage() {
 
     # :command.usage_examples
     printf "Examples:\n"
-    printf "  cli generate example.com\n"
-    printf "  cli generate example.com ./output -f\n"
+    printf "  cli general\n"
+    printf "  cli general -output output.txt\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+qualyscs_sizing_aws_registry_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "qualyscs_sizing_aws registry - Generate sizing for Registry Sensor(s)\n"
+    echo
+
+  else
+    printf "qualyscs_sizing_aws registry - Generate sizing for Registry Sensor(s)\n"
+    echo
+
+  fi
+
+  printf "Usage:\n"
+  printf "  qualyscs_sizing_aws registry [OUTPUT]\n"
+  printf "  qualyscs_sizing_aws registry --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "Arguments:\n"
+
+    # :argument.usage
+    echo "  OUTPUT"
+    printf "    output file\n"
+    echo
+
+    # :command.usage_examples
+    printf "Examples:\n"
+    printf "  cli registry\n"
+    printf "  cli registry -output output.txt\n"
     echo
 
   fi
@@ -155,11 +199,79 @@ inspect_args() {
   fi
 }
 
+# :command.user_lib
+# src/lib/colors.sh
+print_in_color() {
+  local color="$1"
+  shift
+  if [[ -z ${NO_COLOR+x} ]]; then
+    printf "$color%b\e[0m\n" "$*"
+  else
+    printf "%b\n" "$*"
+  fi
+}
+
+red() { print_in_color "\e[31m" "$*"; }
+green() { print_in_color "\e[32m" "$*"; }
+yellow() { print_in_color "\e[33m" "$*"; }
+blue() { print_in_color "\e[34m" "$*"; }
+magenta() { print_in_color "\e[35m" "$*"; }
+cyan() { print_in_color "\e[36m" "$*"; }
+bold() { print_in_color "\e[1m" "$*"; }
+underlined() { print_in_color "\e[4m" "$*"; }
+red_bold() { print_in_color "\e[1;31m" "$*"; }
+green_bold() { print_in_color "\e[1;32m" "$*"; }
+yellow_bold() { print_in_color "\e[1;33m" "$*"; }
+blue_bold() { print_in_color "\e[1;34m" "$*"; }
+magenta_bold() { print_in_color "\e[1;35m" "$*"; }
+cyan_bold() { print_in_color "\e[1;36m" "$*"; }
+red_underlined() { print_in_color "\e[4;31m" "$*"; }
+green_underlined() { print_in_color "\e[4;32m" "$*"; }
+yellow_underlined() { print_in_color "\e[4;33m" "$*"; }
+blue_underlined() { print_in_color "\e[4;34m" "$*"; }
+magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
+cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
+
+# src/lib/yaml.sh
+yaml_load() {
+  local prefix=$2
+  local s='[[:space:]]*' w='[a-zA-Z0-9_]*'
+  local fs
+
+  fs=$(echo @ | tr @ '\034')
+
+  sed -ne "s|^\($s\):|\1|" \
+    -e "s|^\($s\)\($w\)$s:${s}[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
+    -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" "$1" |
+    awk -F"$fs" '{
+      indent = length($1)/2;
+      vname[indent] = $2;
+      for (i in vname) {if (i > indent) {delete vname[i]}}
+      if (length($3) > 0) {
+         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
+         printf("%s%s%s=\"%s\"\n", "'"$prefix"'",vn, $2, $3);
+      }
+    }'
+}
+
 # :command.command_functions
 # :command.function
-qualyscs_sizing_aws_generate_command() {
-  src/qualyscs_sizing_aws_command.sh
- 
+qualyscs_sizing_aws_general_command() {
+  # src/general_command.sh
+  echo "# this file is located in 'src/general_command.sh'"
+  echo "# code for 'qualyscs_sizing_aws general' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
+
+}
+
+# :command.function
+qualyscs_sizing_aws_registry_command() {
+  # src/registry_command.sh
+  echo "# this file is located in 'src/registry_command.sh'"
+  echo "# code for 'qualyscs_sizing_aws registry' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
 
 }
 
@@ -193,10 +305,17 @@ parse_requirements() {
     -*)
       ;;
 
-    generate)
-      action="generate"
+    general)
+      action="general"
       shift
-      qualyscs_sizing_aws_generate_parse_requirements "$@"
+      qualyscs_sizing_aws_general_parse_requirements "$@"
+      shift $#
+      ;;
+
+    registry)
+      action="registry"
+      shift
+      qualyscs_sizing_aws_registry_parse_requirements "$@"
       shift $#
       ;;
 
@@ -237,13 +356,13 @@ parse_requirements() {
 }
 
 # :command.parse_requirements
-qualyscs_sizing_aws_generate_parse_requirements() {
+qualyscs_sizing_aws_general_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
         long_usage=yes
-        qualyscs_sizing_aws_generate_usage
+        qualyscs_sizing_aws_general_usage
         exit
         ;;
 
@@ -255,7 +374,7 @@ qualyscs_sizing_aws_generate_parse_requirements() {
   done
 
   # :command.command_filter
-  action="generate"
+  action="general"
 
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
@@ -270,9 +389,59 @@ qualyscs_sizing_aws_generate_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        if [[ -z ${args[target]+x} ]]; then
+        if [[ -z ${args[output]+x} ]]; then
 
-          args[target]=$1
+          args[output]=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+qualyscs_sizing_aws_registry_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        qualyscs_sizing_aws_registry_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="registry"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args[output]+x} ]]; then
+
+          args[output]=$1
           shift
         else
           printf "invalid argument: %s\n" "$key" >&2
@@ -305,12 +474,21 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
-    "generate")
+    "general")
       if [[ ${args[--help]:-} ]]; then
         long_usage=yes
-        qualyscs_sizing_aws_generate_usage
+        qualyscs_sizing_aws_general_usage
       else
-        qualyscs_sizing_aws_generate_command
+        qualyscs_sizing_aws_general_command
+      fi
+      ;;
+
+    "registry")
+      if [[ ${args[--help]:-} ]]; then
+        long_usage=yes
+        qualyscs_sizing_aws_registry_usage
+      else
+        qualyscs_sizing_aws_registry_command
       fi
       ;;
 
